"""Add makeup flags to Event and create MonthlyQuota

Revision ID: 0d3d85aa5065
Revises: ad96741091d1
Create Date: 2025-06-03 10:14:30.886768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d3d85aa5065'
down_revision = 'ad96741091d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_quota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('required_sessions', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('makeup_for_event_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_makeup', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key('fk_events_makeup_for_event_id', 'events', ['makeup_for_event_id'], ['event_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_events_makeup_for_event_id', type_='foreignkey')
        batch_op.drop_column('is_makeup')
        batch_op.drop_column('makeup_for_event_id')

    op.drop_table('monthly_quota')
    # ### end Alembic commands ###
