"""Add new support-level columns to TrialLog

Revision ID: 23e3e37ef5d8
Revises: 8293caa54f95
Create Date: 2025-05-28 08:52:32.878870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23e3e37ef5d8'
down_revision = '8293caa54f95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trial_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('independent', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('minimal_support', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('moderate_support', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('maximal_support', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('incorrect_new', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trial_log', schema=None) as batch_op:
        batch_op.drop_column('incorrect_new')
        batch_op.drop_column('maximal_support')
        batch_op.drop_column('moderate_support')
        batch_op.drop_column('minimal_support')
        batch_op.drop_column('independent')

    # ### end Alembic commands ###
