"""Add active and notes columns to goal/objective tables

Revision ID: 5d1530d9d58d
Revises: 
Create Date: 2025-03-11 09:59:35.938307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d1530d9d58d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('objective', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objective', schema=None) as batch_op:
        batch_op.drop_column('active')
        batch_op.drop_column('notes')

    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
