"""Add pronouns field to Student table

Revision ID: db08e30c1bfc
Revises: 5d1530d9d58d
Create Date: 2025-03-11 14:26:49.298464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db08e30c1bfc'
down_revision = '5d1530d9d58d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pronouns', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('pronouns')

    # ### end Alembic commands ###
